src/Presentation/Nop.Web/Administration/Models/Payments/PaymentMethodModel.cs
using System.Web.Mvc;
using System.Web.Routing;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Models.Payments
{
    public partial class PaymentMethodModel : BaseNopModel
    {
        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.FriendlyName")]
        [AllowHtml]
        public string FriendlyName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SystemName")]
        [AllowHtml]
        public string SystemName { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.IsActive")]
        public bool IsActive { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.Logo")]
        public string LogoUrl { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportCapture")]
        public bool SupportCapture { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportPartiallyRefund")]
        public bool SupportPartiallyRefund { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportRefund")]
        public bool SupportRefund { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.SupportVoid")]
        public bool SupportVoid { get; set; }

        [NopResourceDisplayName("Admin.Configuration.Payment.Methods.Fields.RecurringPaymentType")]
        public string RecurringPaymentType { get; set; }
        



        public string ConfigurationActionName { get; set; }
        public string ConfigurationControllerName { get; set; }
        public RouteValueDictionary ConfigurationRouteValues { get; set; }
    }
}

src/Presentation/Nop.Web/Administration/Models/Payments/PaymentMethodRestrictionModel.cs
using System.Collections.Generic;
using Nop.Admin.Models.Directory;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Models.Payments
{
    public partial class PaymentMethodRestrictionModel : BaseNopModel
    {
        public PaymentMethodRestrictionModel()
        {
            AvailablePaymentMethods = new List<PaymentMethodModel>();
            AvailableCountries = new List<CountryModel>();
            Resticted = new Dictionary<string, IDictionary<int, bool>>();
        }
        public IList<PaymentMethodModel> AvailablePaymentMethods { get; set; }
        public IList<CountryModel> AvailableCountries { get; set; }

        //[payment method system name] / [customer role id] / [resticted]
        public IDictionary<string, IDictionary<int, bool>> Resticted { get; set; }
    }
}

src/Presentation/Nop.Web/Administration/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using Nop.Admin.Extensions;
using Nop.Admin.Models.Payments;
using Nop.Core;
using Nop.Core.Domain.Payments;
using Nop.Core.Plugins;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;

namespace Nop.Admin.Controllers
{
    public partial class PaymentController : BaseAdminController
	{
		#region Fields

        private readonly IPaymentService _paymentService;
        private readonly PaymentSettings _paymentSettings;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;
	    private readonly ICountryService _countryService;
        private readonly IPluginFinder _pluginFinder;
	    private readonly IWebHelper _webHelper;
	    private readonly ILocalizationService _localizationService;

        #endregion

        #region Ctor

        public PaymentController(IPaymentService paymentService,
            PaymentSettings paymentSettings,
            ISettingService settingService, 
            IPermissionService permissionService,
            ICountryService countryService,
            IPluginFinder pluginFinder,
            IWebHelper webHelper,
            ILocalizationService localizationService)
		{
            this._paymentService = paymentService;
            this._paymentSettings = paymentSettings;
            this._settingService = settingService;
            this._permissionService = permissionService;
            this._countryService = countryService;
            this._pluginFinder = pluginFinder;
            this._webHelper = webHelper;
            this._localizationService = localizationService;
        }

		#endregion 

        #region Methods

        public virtual ActionResult Methods()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public virtual ActionResult Methods(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedKendoGridJson();

            var paymentMethodsModel = new List<PaymentMethodModel>();
            var paymentMethods = _paymentService.LoadAllPaymentMethods();
            foreach (var paymentMethod in paymentMethods)
            {
                var tmp1 = paymentMethod.ToModel();
                tmp1.IsActive = paymentMethod.IsPaymentMethodActive(_paymentSettings);
                tmp1.LogoUrl = paymentMethod.PluginDescriptor.GetLogoUrl(_webHelper);
                paymentMethodsModel.Add(tmp1);
            }
            paymentMethodsModel = paymentMethodsModel.ToList();
            var gridModel = new DataSourceResult
            {
                Data = paymentMethodsModel,
                Total = paymentMethodsModel.Count
            };

            return Json(gridModel);
        }

        [HttpPost]
        public virtual ActionResult MethodUpdate([Bind(Exclude = "ConfigurationRouteValues")] PaymentMethodModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var pm = _paymentService.LoadPaymentMethodBySystemName(model.SystemName);
            if (pm.IsPaymentMethodActive(_paymentSettings))
            {
                if (!model.IsActive)
                {
                    //mark as disabled
                    _paymentSettings.ActivePaymentMethodSystemNames.Remove(pm.PluginDescriptor.SystemName);
                    _settingService.SaveSetting(_paymentSettings);
                }
            }
            else
            {
                if (model.IsActive)
                {
                    //mark as active
                    _paymentSettings.ActivePaymentMethodSystemNames.Add(pm.PluginDescriptor.SystemName);
                    _settingService.SaveSetting(_paymentSettings);
                }
            }
            var pluginDescriptor = pm.PluginDescriptor;
            pluginDescriptor.FriendlyName = model.FriendlyName;
            pluginDescriptor.DisplayOrder = model.DisplayOrder;
            PluginFileParser.SavePluginDescriptionFile(pluginDescriptor);
            //reset plugin cache
            _pluginFinder.ReloadPlugins();

            return new NullJsonResult();
        }

        public virtual ActionResult ConfigureMethod(string systemName)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var pm = _paymentService.LoadPaymentMethodBySystemName(systemName);
            if (pm == null)
                //No payment method found with the specified id
                return RedirectToAction("Methods");

            var model = pm.ToModel();
            string actionName, controllerName;
            RouteValueDictionary routeValues;
            pm.GetConfigurationRoute(out actionName, out controllerName, out routeValues);
            model.ConfigurationActionName = actionName;
            model.ConfigurationControllerName = controllerName;
            model.ConfigurationRouteValues = routeValues;
            return View(model);
        }

        public virtual ActionResult MethodRestrictions()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var model = new PaymentMethodRestrictionModel();

            var paymentMethods = _paymentService.LoadAllPaymentMethods();
            var countries = _countryService.GetAllCountries(showHidden: true);
            foreach (var pm in paymentMethods)
            {
                model.AvailablePaymentMethods.Add(pm.ToModel());
            }
            foreach (var c in countries)
            {
                model.AvailableCountries.Add(c.ToModel());
            }
            foreach (var pm in paymentMethods)
            {
                var restictedCountries = _paymentService.GetRestictedCountryIds(pm);
                foreach (var c in countries)
                {
                    bool resticted = restictedCountries.Contains(c.Id);
                    if (!model.Resticted.ContainsKey(pm.PluginDescriptor.SystemName))
                        model.Resticted[pm.PluginDescriptor.SystemName] = new Dictionary<int, bool>();
                    model.Resticted[pm.PluginDescriptor.SystemName][c.Id] = resticted;
                }
            }

            return View(model);
        }

        [HttpPost, ActionName("MethodRestrictions")]
        public virtual ActionResult MethodRestrictionsSave(FormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            var paymentMethods = _paymentService.LoadAllPaymentMethods();
            var countries = _countryService.GetAllCountries(showHidden: true);

            foreach (var pm in paymentMethods)
            {
                string formKey = "restrict_" + pm.PluginDescriptor.SystemName;
                var countryIdsToRestrict = (form[formKey] != null ? form[formKey].Split(new [] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList() : new List<string>())
                    .Select(x => Convert.ToInt32(x)).ToList();

                var newCountryIds = new List<int>();
                foreach (var c in countries)
                {
                    if (countryIdsToRestrict.Contains(c.Id))
                    {
                        newCountryIds.Add(c.Id);
                    }
                }
                _paymentService.SaveRestictedCountryIds(pm, newCountryIds);
            }

            SuccessNotification(_localizationService.GetResource("Admin.Configuration.Payment.MethodRestrictions.Updated"));
            return RedirectToAction("MethodRestrictions");
        }

        #endregion
    }
}

src/Presentation/Nop.Web/Administration/Views/Payment/ConfigureMethod.cshtml
@model PaymentMethodModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Payment.Methods.Configure").Text + " - " + Model.FriendlyName;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Payment methods");
}

<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.Configuration.Payment.Methods.Configure") - @Model.FriendlyName
        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Configuration.Payment.Methods.BackToList").Text, "Methods")</small>
    </h1>
    <div class="pull-right">
        &nbsp;
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        @if (!String.IsNullOrEmpty(Model.ConfigurationActionName))
        {
            @Html.Action(Model.ConfigurationActionName, Model.ConfigurationControllerName, Model.ConfigurationRouteValues);
        }
        else
        {
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @T("Admin.Common.ConfigurationNotRequired")
                    </div>
                </div>
            </div>
        }
    </div>
</div>

src/Presentation/Nop.Web/Administration/Views/Payment/MethodRestrictions.cshtml
@model PaymentMethodRestrictionModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Payment.MethodRestrictions").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Payment method restrictions");
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Payment.MethodRestrictions")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>@T("Admin.Configuration.Payment.MethodRestrictions.Description")</p>
                        @if (Model.AvailablePaymentMethods.Count == 0)
                        {
                            <text>No payment methods installed</text>
                        }
                        else if (Model.AvailableCountries.Count == 0)
                        {
                            <text>No countries available</text>
                        }
                        else
                        {
                            <script type="text/javascript">
                                $(document).ready(function () {
                                    @foreach (var pm in Model.AvailablePaymentMethods)
                                    {
                                        var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                        <text>
                                            $('#selectall-@(systemNameWithoutDot)').click(function () {
                                                $('.restrict_@(systemNameWithoutDot)').attr('checked', $(this).is(':checked')).change();
                                            });
                                        </text>
                                    }
                                });
                            </script>
                                    <table class="table table-hover table-bordered">
                                        <tbody>
                                            <tr>
                                                <th scope="col" style="padding-top: 14px;">
                                                    <strong>@T("Admin.Configuration.Payment.MethodRestrictions.Country")</strong>
                                                </th>
                                                @foreach (var pm in Model.AvailablePaymentMethods)
                                                {
                                                    var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                                    <th scope="col">
                                                        <div class="checkbox">
                                                            <label>
                                                                <input type="checkbox" id="selectall-@(systemNameWithoutDot)" />
                                                                <strong>@pm.FriendlyName</strong>
                                                            </label>
                                                        </div>
                                                    </th>
                                                }
                                            </tr>
                                            @foreach (var c in Model.AvailableCountries)
                                            {
                                                <tr>
                                                    <td>
                                                        <span>@c.Name</span>
                                                    </td>
                                                    @foreach (var pm in Model.AvailablePaymentMethods)
                                                    {
                                                        var resticted = Model.Resticted.ContainsKey(pm.SystemName) && Model.Resticted[pm.SystemName][c.Id];

                                                        var systemNameWithoutDot = pm.SystemName.Replace(".", "");
                                                        <td>
                                                            <input class="restrict_@(systemNameWithoutDot)" type="checkbox" value="@(c.Id)" name="restrict_@(pm.SystemName)" @(resticted ? " checked=checked" : null) />
                                                        </td>
                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

src/Presentation/Nop.Web/Administration/Views/Payment/Methods.cshtml
@{    
    //page title
    ViewBag.Title = T("Admin.Configuration.Payment.Methods").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Payment methods");
}

@Html.AntiForgeryToken()
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.Configuration.Payment.Methods")
    </h1>
    <div class="pull-right">
       &nbsp;
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="paymentmethods-grid"></div>

                    <script>
                        $(document).ready(function() {
                            $("#paymentmethods-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("Methods", "Payment"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: addAntiForgeryToken
                                        },
                                        update: {
                                            url: "@Html.Raw(Url.Action("MethodUpdate", "Payment"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: addAntiForgeryToken
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "SystemName",
                                            fields: {
                                                FriendlyName: { editable: true, type: "string" },
                                                SystemName: { editable: false, type: "string" },
                                                LogoUrl: { editable: false, type: "string" },
                                                SupportCapture: { editable: false, type: "boolean" },
                                                SupportRefund: { editable: false, type: "boolean" },
                                                SupportPartiallyRefund: { editable: false, type: "boolean" },
                                                SupportVoid: { editable: false, type: "boolean" },
                                                RecurringPaymentType: { editable: false, type: "string" },
                                                DisplayOrder: { editable: true, type: "number" },
                                                IsActive: { editable: true, type: "boolean" }
                                            }
                                        }
                                    },
                                    requestEnd: function(e) {
                                        if (e.type == "update") {
                                            this.read();
                                        }
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    numeric: false,
                                    previousNext: false,
                                    info: false,
                                    @Html.Partial("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                {
                                    field: "FriendlyName",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.FriendlyName")",
                                    width: 250
                                }, {
                                    field: "SystemName",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.SystemName")",
                                    width: 250
                                }, {
                                    field: "LogoUrl",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.Logo")",
                                    width: 100,
                                    template: '<img src="#=LogoUrl#" />'
                                }, {
                                    field: "SupportCapture",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportCapture")",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '# if(SupportCapture) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                }, {
                                    field: "SupportRefund",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportRefund")",
                                    width: 100,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '# if(SupportRefund) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                }, {
                                    field: "SupportPartiallyRefund",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportPartiallyRefund")",
                                    width: 150,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '# if(SupportPartiallyRefund) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                }, {
                                    field: "SupportVoid",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.SupportVoid")",
                                    width: 100,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '# if(SupportVoid) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                }, {
                                    field: "RecurringPaymentType",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.RecurringPaymentType")",
                                    width: 250
                                }, {
                                    field: "DisplayOrder",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.DisplayOrder")",
                                    //integer format
                                    format: "{0:0}",
                                    width: 150
                                }, {
                                    field: "IsActive",
                                    title: "@T("Admin.Configuration.Payment.Methods.Fields.IsActive")",
                                    width: 100,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '# if(IsActive) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                }, {
                                    field: "SystemName",
                                    title: "@T("Admin.Configuration.Payment.Methods.Configure")",
                                    width: 150,
                                    template: '<a class="btn btn-default" href="ConfigureMethod?systemName=#=SystemName#"><i class="fa fa-cog"></i>@T("Admin.Configuration.Payment.Methods.Configure")</a>'
                                }, {
                                    command: {
                                        name: "edit",
                                        text: {
                                            edit: "@T("Admin.Common.Edit")",
                                            update: "@T("Admin.Common.Update")",
                                            cancel: "@T("Admin.Common.Cancel")"
                                        }
                                    },
                                    title: "@T("Admin.Common.Edit")",
                                        width: 150
                                    }
                                ]
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>